
<script type="text/javascript" src="https://clic.local/Assets/vendor/layout/easyUi/easyui.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/layout/fooTable/standalone.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/layout/jexcel/jexcel.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/layout/jexcel/jsuites/jsuites.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/date/moment/moment.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/date/flatpickr/datetime.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/date/flatpickr/init.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/range/range.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/other/phone-code/intlTelInput-jquery.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/color/spectrum/spectrum.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/number/accounting.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/number/jquery.priceformat.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/number/touchSpin/jquery.bootstrap-touchspin.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/autocomplete/easyAutoComplete/easy-autocomplete.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/select/tomSelect/js/tom-select.complete.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/photo/cropper/cropper.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/photo/cropper/jquery-cropper.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/init/cropper.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/radioCheck/radioCheck.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/select/dualList/multi.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/init/main.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/init/session.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/photo/feather/featherlight.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/wysiwyg/jodit/jodit.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/vendor/sessionManager/jquery.timed-lock.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/files/jquery.are-you-sure.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/files/jquery.autotab.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/files/jquery.inputlimiter.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/files/jquery.counter.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/files/jquery.inputmask.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/other/holder.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/other/autosize.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/other/responsive-tables.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/other/pstrength.min.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/init/other.js"></script>
	<script type="text/javascript" src="https://clic.local/Assets/js/init/forms.js"></script>
	<script type="text/javascript" src="https://clic.local/Backend-erp/js/init.js"></script>